### ISSUE TITLE
wget is needed for Maven

### ISSUE THREAD

**Issue by BalazsGyarmati** [TremoloSecurity/OpenUnisonS2IDocker#3]
I wanted to build OpenUnison image with s2i when I ran into this error:
```
Looking for OpenUnison war file or pom.xml...
numWarFiles: 0
Found pom.xml... attempting to build with 'mvn '

Installing Maven 3.6.1
/usr/local/bin/s2i/assemble: line 68: wget: command not found
Build failed
ERROR: An error occurred: non-zero (13) exit code from docker.io/tremolosecurity/openunisons2idocker:latest
```

It turned out that wget is not installed in the image I've pulled from Docker Hub (I used the latest tag).

I can create a pull request for your Dockerfile, but I thought it would be better to discuss first where to make a change :) (/usr/local/bin/s2i/assemble or the image)

**Comment by mlbiam** [comment]
Sorry about that. Should be fixed now

**Comment by BalazsGyarmati** [comment]
No problem, thanks for the quick fix.
